let data = [
  {
    name: 'Indochinese Spitting Cobra',
    latin_name: 'Naja siamensis',
    animal_type: 'Reptile',
    active_time: 'Nocturnal',
    length_min: '3',
    length_max: '4',
    weight_min: '3.2',
    weight_max: '3.5',
    lifespan: '25',
    habitat: 'Forest',
    diet: 'Rodents, snakes and other small animals',
    geo_range: 'Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/d6/Naja-siamensis-indochinese-spitting-cobra-southwest-thailand.jpg',
    id: 94,
  },
  {
    name: 'Andean Bear',
    latin_name: 'Tremarctos ornatus',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '4.3',
    length_max: '6.6',
    weight_min: '220',
    weight_max: '440',
    lifespan: '26',
    habitat: 'Mountain forests, grasslands, and scrub dessert',
    diet: 'Primarily fruits, bromeliads, bamboo, cactus and other plants, some small animals',
    geo_range: 'Northwestern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/fa/Tremarctos_ornatus_25.jpg',
    id: 13,
  },
  {
    name: 'Hellbender',
    latin_name: 'Cryptobranchus alleganiensis',
    animal_type: 'Amphibian',
    active_time: 'Nocturnal',
    length_min: '1',
    length_max: '2',
    weight_min: '4',
    weight_max: '5',
    lifespan: '30',
    habitat: 'Rivers and streams',
    diet: 'Crayfish, small fish and aquatic insects',
    geo_range: 'Midwestern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/ff/Hellbender_Cryptobranchus_alleganiensis.jpg',
    id: 86,
  },
  {
    name: 'Mosquitofish',
    latin_name: 'Gambusia affinis',
    animal_type: 'Fish',
    active_time: 'Diurnal',
    length_min: '0.2',
    length_max: '0.23',
    weight_min: '0.003',
    weight_max: '0.004',
    lifespan: '3',
    habitat: 'Hot springs, rivers, streams, lakes, swamps,',
    diet: 'Mosquito larva',
    geo_range: 'Gulf of Mexico',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/5c/Mosquitofish.jpg',
    id: 120,
  },
  {
    name: 'Fairy Bluebird',
    latin_name: 'Irena puella',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.75',
    length_max: '0.9',
    weight_min: '0.03',
    weight_max: '0.18',
    lifespan: '12',
    habitat: 'Forest',
    diet: 'Fruit, nectar, and insects',
    geo_range: 'South and Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3f/Fairy_bluebird_male_-_Irena_puella.jpg',
    id: 69,
  },
  {
    name: 'Malayan Tiger',
    latin_name: 'Panthera tigris jacksoni',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '7.6',
    length_max: '9.3',
    weight_min: '220',
    weight_max: '400',
    lifespan: '15',
    habitat: 'Forest',
    diet: 'Deer, wild pigs, and cattle',
    geo_range: 'Malaysia and southern Thailand',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/6/62/MalayanTiger01.jpg',
    id: 113,
  },
  {
    name: 'Ornate Horned Frog',
    latin_name: 'Ceratophrys ornata',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.25',
    length_max: '5',
    weight_min: '0.85',
    weight_max: '1',
    lifespan: '6',
    habitat: 'Rainforest',
    diet: 'Lizards, mice, frogs, insects, and other small animals',
    geo_range: 'Argentina, Uruguay, and southern Brazil',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/2b/Mr_Wiggles_7-20-07_%28870844637%29.jpg',
    id: 128,
  },
  {
    name: "Mueller's Gibbon",
    latin_name: 'Hylobates muelleri',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.6',
    length_max: '1.8',
    weight_min: '11.5',
    weight_max: '12.5',
    lifespan: '40',
    habitat: 'Tropical rainforest',
    diet: 'Primarily fruit; some leaves, flowers, and invertebrates',
    geo_range: 'Borneo, Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a0/MuellersGibbon.jpg',
    id: 121,
  },
  {
    name: 'Scarlet Ibis',
    latin_name: 'Eudocimus ruber',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2.1',
    length_max: '2.2',
    weight_min: '1.3',
    weight_max: '1.4',
    lifespan: '12',
    habitat: 'Coastal wetlands',
    diet: 'Small crayfish, snails and amphibians',
    geo_range: 'Northern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/f7/Scarlet_Ibis_SMTC.jpg',
    id: 159,
  },
  {
    name: 'Black-breasted Leaf Turtle',
    latin_name: 'Geoemyda spengleri',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.2',
    length_max: '0.35',
    weight_min: '0.2',
    weight_max: '0.4',
    lifespan: '20',
    habitat: 'Mountain forest',
    diet: 'Invertebrates and fruit',
    geo_range: 'China and Vietnam',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/d6/Stavenn_Geoemyda_spengleri.jpg',
    id: 35,
  },
  {
    name: 'Indochinese Spitting Cobra',
    latin_name: 'Naja siamensis',
    animal_type: 'Reptile',
    active_time: 'Nocturnal',
    length_min: '3',
    length_max: '4',
    weight_min: '3.2',
    weight_max: '3.5',
    lifespan: '25',
    habitat: 'Forest',
    diet: 'Rodents, snakes and other small animals',
    geo_range: 'Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/d6/Naja-siamensis-indochinese-spitting-cobra-southwest-thailand.jpg',
    id: 94,
  },
  {
    name: 'Andean Bear',
    latin_name: 'Tremarctos ornatus',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '4.3',
    length_max: '6.6',
    weight_min: '220',
    weight_max: '440',
    lifespan: '26',
    habitat: 'Mountain forests, grasslands, and scrub dessert',
    diet: 'Primarily fruits, bromeliads, bamboo, cactus and other plants, some small animals',
    geo_range: 'Northwestern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/fa/Tremarctos_ornatus_25.jpg',
    id: 13,
  },
  {
    name: 'Hellbender',
    latin_name: 'Cryptobranchus alleganiensis',
    animal_type: 'Amphibian',
    active_time: 'Nocturnal',
    length_min: '1',
    length_max: '2',
    weight_min: '4',
    weight_max: '5',
    lifespan: '30',
    habitat: 'Rivers and streams',
    diet: 'Crayfish, small fish and aquatic insects',
    geo_range: 'Midwestern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/ff/Hellbender_Cryptobranchus_alleganiensis.jpg',
    id: 86,
  },
  {
    name: 'Mosquitofish',
    latin_name: 'Gambusia affinis',
    animal_type: 'Fish',
    active_time: 'Diurnal',
    length_min: '0.2',
    length_max: '0.23',
    weight_min: '0.003',
    weight_max: '0.004',
    lifespan: '3',
    habitat: 'Hot springs, rivers, streams, lakes, swamps,',
    diet: 'Mosquito larva',
    geo_range: 'Gulf of Mexico',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/5c/Mosquitofish.jpg',
    id: 120,
  },
  {
    name: 'Fairy Bluebird',
    latin_name: 'Irena puella',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.75',
    length_max: '0.9',
    weight_min: '0.03',
    weight_max: '0.18',
    lifespan: '12',
    habitat: 'Forest',
    diet: 'Fruit, nectar, and insects',
    geo_range: 'South and Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3f/Fairy_bluebird_male_-_Irena_puella.jpg',
    id: 69,
  },
  {
    name: 'Malayan Tiger',
    latin_name: 'Panthera tigris jacksoni',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '7.6',
    length_max: '9.3',
    weight_min: '220',
    weight_max: '400',
    lifespan: '15',
    habitat: 'Forest',
    diet: 'Deer, wild pigs, and cattle',
    geo_range: 'Malaysia and southern Thailand',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/6/62/MalayanTiger01.jpg',
    id: 113,
  },
  {
    name: 'Ornate Horned Frog',
    latin_name: 'Ceratophrys ornata',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.25',
    length_max: '5',
    weight_min: '0.85',
    weight_max: '1',
    lifespan: '6',
    habitat: 'Rainforest',
    diet: 'Lizards, mice, frogs, insects, and other small animals',
    geo_range: 'Argentina, Uruguay, and southern Brazil',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/2b/Mr_Wiggles_7-20-07_%28870844637%29.jpg',
    id: 128,
  },
  {
    name: "Mueller's Gibbon",
    latin_name: 'Hylobates muelleri',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.6',
    length_max: '1.8',
    weight_min: '11.5',
    weight_max: '12.5',
    lifespan: '40',
    habitat: 'Tropical rainforest',
    diet: 'Primarily fruit; some leaves, flowers, and invertebrates',
    geo_range: 'Borneo, Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a0/MuellersGibbon.jpg',
    id: 121,
  },
  {
    name: 'Scarlet Ibis',
    latin_name: 'Eudocimus ruber',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2.1',
    length_max: '2.2',
    weight_min: '1.3',
    weight_max: '1.4',
    lifespan: '12',
    habitat: 'Coastal wetlands',
    diet: 'Small crayfish, snails and amphibians',
    geo_range: 'Northern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/f7/Scarlet_Ibis_SMTC.jpg',
    id: 159,
  },
  {
    name: 'Black-breasted Leaf Turtle',
    latin_name: 'Geoemyda spengleri',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.2',
    length_max: '0.35',
    weight_min: '0.2',
    weight_max: '0.4',
    lifespan: '20',
    habitat: 'Mountain forest',
    diet: 'Invertebrates and fruit',
    geo_range: 'China and Vietnam',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/d6/Stavenn_Geoemyda_spengleri.jpg',
    id: 35,
  },
  {
    name: 'White-cheeked Bulbul',
    latin_name: 'Pycnonotus leucotis',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.58',
    length_max: '0.63',
    weight_min: '0.05',
    weight_max: '0.06',
    lifespan: '9',
    habitat: 'Grassland, shrubland and woodland',
    diet: 'Fruit and insects',
    geo_range: 'Middle East and Western Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3b/White-eared_bulbul.jpg',
    id: 188,
  },
  {
    name: 'Buff-Cheeked Gibbon',
    latin_name: 'Hylobales gabriellae',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '2',
    weight_min: '10',
    weight_max: '12.5',
    lifespan: '50',
    habitat: 'Tropical forest',
    diet: 'Fruit, leaves, and invertebrates',
    geo_range: 'Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/c6/Nomascus_gabriellae_25.JPG',
    id: 46,
  },
  {
    name: 'Amazon Milk Frog',
    latin_name: 'Trachycephalus resinifictrix',
    animal_type: 'Amphibian',
    active_time: 'Nocturnal',
    length_min: '0.21',
    length_max: '0.33',
    weight_min: '0.05',
    weight_max: '0.05',
    lifespan: '25',
    habitat: 'Tropical rainforest',
    diet: 'Insects, spiders, and other small animals',
    geo_range: 'Northern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/12/Amazon_Milk_Frog_%28Trachycephalus_resinifictrix%29%2C_CMN.jpg',
    id: 10,
  },
  {
    name: "Coquerel's Sifaka",
    latin_name: 'Propithecus coquereli',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.4',
    length_max: '1.7',
    weight_min: '7.5',
    weight_max: '11',
    lifespan: '11',
    habitat: 'Forest',
    diet: 'Leaves, fruit, and flowers',
    geo_range: 'Northwestern Madagascar',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/4/4e/Propithecus_coquereli_02.jpg',
    id: 57,
  },
  {
    name: 'Cape Porcupine',
    latin_name: 'Hystrix africaeaustralis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '2.5',
    length_max: '3',
    weight_min: '40',
    weight_max: '65',
    lifespan: '15',
    habitat: 'Savannah, scrubland and forest',
    diet: 'Fruit, roots, tubers and bulbs',
    geo_range: 'Central and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/b4/Hystrix_africaeaustralis_Blijdorp_Rotterdam.JPG',
    id: 50,
  },
  {
    name: 'Madagascar Giant Day Gecko',
    latin_name: 'Phelsuma madagascariensis grandis',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.75',
    length_max: '1',
    weight_min: '0.13',
    weight_max: '0.15',
    lifespan: '15',
    habitat: 'Forest',
    diet: 'Insects and other small animals, fruit, and honey',
    geo_range: 'Northern Madagascar',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/8/8b/Madagascar_giant_day_gecko_%28Phelsuma_grandis%29_Nosy_Komba.jpg',
    id: 109,
  },
  {
    name: 'Barn Owl',
    latin_name: 'Tyto alba',
    animal_type: 'Bird',
    active_time: 'Nocturnal',
    length_min: '1',
    length_max: '1.5',
    weight_min: '1.2',
    weight_max: '1.4',
    lifespan: '20',
    habitat: 'Grassland, desert, marsh, and agricultural fields',
    diet: 'Small mammals such as mice, voles, and shrews',
    geo_range: 'Worldwide',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/c6/Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_%281%29.jpg',
    id: 25,
  },
  {
    name: 'Eurasian Eagle Owl',
    latin_name: 'Bubo bubo',
    animal_type: 'Bird',
    active_time: 'Nocturnal',
    length_min: '2',
    length_max: '2.5',
    weight_min: '3.5',
    weight_max: '9',
    lifespan: '60',
    habitat: 'Rocky areas, woodland, and grassland',
    diet: 'Mammals, such as rabbits and rodents, and birds',
    geo_range: 'Europe and Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/14/Bubo_bubo_3_%28Martin_Mecnarowski%29.jpg',
    id: 68,
  },
  {
    name: 'Meerkat',
    latin_name: 'Suricata suricatta',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '0.9',
    length_max: '1',
    weight_min: '1.5',
    weight_max: '2',
    lifespan: '9',
    habitat: 'Savannah',
    diet: 'Insects, lizards, scorpions, and other small animals',
    geo_range: 'Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/9a/Meerkat_%28Suricata_suricatta%29_Tswalu.jpg',
    id: 117,
  },
  {
    name: 'Kea',
    latin_name: 'Nestor notabilis',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '1.7',
    weight_min: '1.7',
    weight_max: '1.9',
    lifespan: '8',
    habitat: 'Mountain forest',
    diet: 'Plants, animals, and carrion',
    geo_range: 'New Zealand',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/34/Nestor_notabilis_-Fiordland%2C_New_Zealand-8b.jpg',
    id: 97,
  },
  {
    name: 'Masai Giraffe',
    latin_name: 'Giraffa camelopardalis tippelskirchi',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '15',
    length_max: '17',
    weight_min: '1200',
    weight_max: '4250',
    lifespan: '13',
    habitat: 'Savanna and woodland',
    diet: 'Leaves, shoots, and fruits',
    geo_range: 'Southern Kenya and Tanzania',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3b/Mannetjes_masaigiraffe_in_de_Serengeti%2C_Tanzania%2C_-12_januari_2013_a.jpg',
    id: 114,
  },
  {
    name: 'Longnose Gar',
    latin_name: 'Lepisosteus osseus',
    animal_type: 'Fish',
    active_time: 'Nocturnal',
    length_min: '2',
    length_max: '6',
    weight_min: '1.1',
    weight_max: '7.7',
    lifespan: '20',
    habitat: 'Rivers, lakes, reserviors and estuaries',
    diet: 'Small fish',
    geo_range: 'North America east of the Mississippi River',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a6/Longnose_gar%2C_Boston_Aquarium.JPG',
    id: 108,
  },
  {
    name: 'Llama',
    latin_name: 'Lama glama',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '5.6',
    length_max: '5.9',
    weight_min: '285',
    weight_max: '340',
    lifespan: '25',
    habitat: 'High plateau',
    diet: 'Grass',
    geo_range: 'Andes Mountains of South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/cd/Black_Llama.jpg',
    id: 107,
  },
  {
    name: 'Snow Leopard',
    latin_name: 'Uncia uncia',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '2.5',
    length_max: '4.9',
    weight_min: '77',
    weight_max: '120',
    lifespan: '14',
    habitat:
      'Mountain regions, including grassland, scrubland, and open woodland',
    diet: 'Primarily blue sheep and ibex; some other hoofed mammals, hares, rodents and birds',
    geo_range: 'Central Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a5/Irbis4.JPG',
    id: 164,
  },
  {
    name: 'Wood Duck',
    latin_name: 'Aix sponsa',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '1.7',
    weight_min: '1.8',
    weight_max: '2',
    lifespan: '15',
    habitat: 'Wetlands and forest',
    diet: 'Seeds, fruit and invertebrates',
    geo_range: 'North America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/d3/Wood_Duck_%28Aix_sponsa%29%2C_Parc_du_Rouge-Clo%C3%AEtre%2C_Brussels.jpg',
    id: 193,
  },
  {
    name: 'White-throated Monitor',
    latin_name: 'Varanus albigularis',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '3.3',
    length_max: '6',
    weight_min: '20',
    weight_max: '25',
    lifespan: '20',
    habitat: 'Savanna',
    diet: 'Birds, insects, snails, and invertebrates',
    geo_range: 'Central and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/0e/Rock_monitor%2C_Varanus_albigularis%2C_also_called_commonly_the_white-throated_monitor_or_leguaan._%2848206382456%29.jpg',
    id: 192,
  },
  {
    name: 'Buff-crested bustard',
    latin_name: 'Eudpodotis ruficrista',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.4',
    length_max: '1.6',
    weight_min: '1.5',
    weight_max: '2',
    lifespan: '7',
    habitat: 'Semi-desert, bush, savanna and woodland',
    diet: 'Arthropods, seeds, fruit and grains',
    geo_range: 'Central southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/36/Crested_Bustard_-_Eupodotis_ruficrista_gindiana.jpg',
    id: 47,
  },
  {
    name: 'Naked Mole-rat',
    latin_name: 'Heterocephalus glaber',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '0.25',
    length_max: '0.33',
    weight_min: '0.06',
    weight_max: '0.13',
    lifespan: '30',
    habitat: 'Savannah',
    diet: 'Roots and tubers',
    geo_range: 'Eastern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/02/Nacktmull.jpg',
    id: 122,
  },
  {
    name: 'Cougar',
    latin_name: 'Puma concolor',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '3.4',
    length_max: '6.4',
    weight_min: '80',
    weight_max: '225',
    lifespan: '13',
    habitat:
      'Desert, savannah, tropical rainforest, forest, scrubland, and mountain areas',
    diet: 'Mammals ranging in size from mice to white-tail deer',
    geo_range: 'Western North America, Florida, and Central and South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/d6/Mountain_Lion_in_Glacier_National_Park.jpg',
    id: 59,
  },
  {
    name: 'Blue-tongued Skink',
    latin_name: 'Tiliqua scincoides scincoides',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '1.7',
    weight_min: '0.63',
    weight_max: '1.3',
    lifespan: '20',
    habitat: 'Grassland, forest, and desert',
    diet: 'Snails and other invertebrates, carrion, fruits, berries, and flowers',
    geo_range: 'Australia, including Tasmania',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/7/7b/Tiliqua_scincoides_scincoides_01.jpg',
    id: 41,
  },
  {
    name: "Major Mitchell's Cockatoo",
    latin_name: 'Cacatua leadbeateri',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1',
    length_max: '1.2',
    weight_min: '0.9',
    weight_max: '0.95',
    lifespan: '60',
    habitat: 'Forest and grassland',
    diet: 'Seeds, nuts, fruits, berries, and roots',
    geo_range: 'Australia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/7/74/Major_Mitchell%27s_Cockatoo_1_-_Mt_Grenfell.jpg',
    id: 112,
  },
  {
    name: 'Ring-tailed Lemur',
    latin_name: 'Lemur catta',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.3',
    length_max: '1.5',
    weight_min: '5',
    weight_max: '8',
    lifespan: '16',
    habitat: 'Forest',
    diet: 'Fruit, leaves, flowers and insects',
    geo_range: 'Southern and Southwestern Madagascar',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/0b/Ring-tailed_lemur_%28Lemur_catta%29.jpg',
    id: 151,
  },
  {
    name: 'Golden-headed Lion Tamarin',
    latin_name: 'Leontopithecus chrysomelas',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '0.7',
    length_max: '1.1',
    weight_min: '1',
    weight_max: '1.5',
    lifespan: '11',
    habitat: 'Tropical rainforest',
    diet: 'Fruit, flowers, nectar, gum and small animals',
    geo_range: 'Eastern Brazil',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3d/Leontopithecus_chrysomelas_%28portrait%29.jpg',
    id: 76,
  },
  {
    name: 'White-Handed Gibbon',
    latin_name: 'Hylobates lar',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.42',
    length_max: '1.92',
    weight_min: '10',
    weight_max: '17',
    lifespan: '16',
    habitat: 'Tropical forest',
    diet: 'Fruits, leaves, insects, and flowers',
    geo_range: 'Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/38/Hylobates_lar_pair_of_white_and_black_01.jpg',
    id: 190,
  },
  {
    name: 'African Pygmy Falcon',
    latin_name: 'Polihierax semitorquatus',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.6',
    length_max: '0.7',
    weight_min: '0.1',
    weight_max: '0.16',
    lifespan: '7',
    habitat: 'Savannah',
    diet: 'Insects, lizards, birds and rodents',
    geo_range: 'Eastern and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/7/74/African_Pygmy_Falcon_Female.jpg',
    id: 6,
  },
  {
    name: 'Ornate Monitor',
    latin_name: 'Varanus ornatus',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '6',
    length_max: '6.5',
    weight_min: '11',
    weight_max: '13',
    lifespan: '13',
    habitat: 'Woodland, savanna, scrubland, swamps, lakes, and rivers',
    diet: 'Insects, fish, frogs, reptiles, birds, mammals, and carrion',
    geo_range: 'Central and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/90/OrnateMonitor.jpg',
    id: 129,
  },
  {
    name: 'Buff-crested bustard',
    latin_name: 'Eudpodotis ruficrista',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.4',
    length_max: '1.6',
    weight_min: '1.5',
    weight_max: '2',
    lifespan: '7',
    habitat: 'Semi-desert, bush, savanna and woodland',
    diet: 'Arthropods, seeds, fruit and grains',
    geo_range: 'Central southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/36/Crested_Bustard_-_Eupodotis_ruficrista_gindiana.jpg',
    id: 47,
  },
  {
    name: 'Rough Green Snake',
    latin_name: 'Opheodrys aestivus',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '1.83',
    length_max: '2.67',
    weight_min: '0.02',
    weight_max: '0.12',
    lifespan: '10',
    habitat: 'Moist woodland',
    diet: 'Insects and spiders',
    geo_range: 'Southeastern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/bd/Rough_Green_Snake.jpg',
    id: 153,
  },
  {
    name: 'Saddle-billed Stork',
    latin_name: 'Ephippiorhynchus senegalensis',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '4.75',
    length_max: '4.92',
    weight_min: '11',
    weight_max: '16',
    lifespan: '12',
    habitat: 'Freshwater marshes, rivers, floodplains and lake shores',
    diet: 'Mainly fish, some other small aquatic creatures, insects and carrion',
    geo_range: 'Central Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/e/e6/Saddle-billed_Stork_in_flight.jpg',
    id: 156,
  },
  {
    name: 'African Lion',
    latin_name: 'Panthera leo',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '8.5',
    length_max: '10',
    weight_min: '330',
    weight_max: '530',
    lifespan: '16',
    habitat: 'Savannah, woodland, and desert',
    diet: 'Hoofed mammals, hares, small birds and reptiles',
    geo_range: 'Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/7/73/Lion_waiting_in_Namibia.jpg',
    id: 3,
  },
  {
    name: 'Rainbow Boa',
    latin_name: 'Epicrates cenchria',
    animal_type: 'Reptile',
    active_time: 'Nocturnal',
    length_min: '5',
    length_max: '7',
    weight_min: '2',
    weight_max: '5',
    lifespan: '20',
    habitat: 'Woodland and savanna',
    diet: 'Small mammals and birds',
    geo_range: 'South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a4/EpicratesCenchriaCenchria1.jpg',
    id: 143,
  },
  {
    name: 'Impala',
    latin_name: 'Aepyceros melampus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '4.2',
    length_max: '4.7',
    weight_min: '99',
    weight_max: '132',
    lifespan: '15',
    habitat: 'Savannah and woodland',
    diet: 'Grasses and leaves',
    geo_range: 'Southern and East Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/e/e1/Trotting_impala_ram%2C_crop.jpg',
    id: 91,
  },
  {
    name: 'Raggiana Bird-of-paradise',
    latin_name: 'Paradisaea raggiana',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.9',
    length_max: '1.1',
    weight_min: '0.44',
    weight_max: '0.75',
    lifespan: '8',
    habitat: 'Forest',
    diet: 'Fruit, berries, insects, frogs, and lizards',
    geo_range: 'New Guinea',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/c6/Raggiana_bird_of_paradise.jpg',
    id: 142,
  },
  {
    name: "Mueller's Gibbon",
    latin_name: 'Hylobates muelleri',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.6',
    length_max: '1.8',
    weight_min: '11.5',
    weight_max: '12.5',
    lifespan: '40',
    habitat: 'Tropical rainforest',
    diet: 'Primarily fruit; some leaves, flowers, and invertebrates',
    geo_range: 'Borneo, Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a0/MuellersGibbon.jpg',
    id: 121,
  },
  {
    name: 'Hellbender',
    latin_name: 'Cryptobranchus alleganiensis',
    animal_type: 'Amphibian',
    active_time: 'Nocturnal',
    length_min: '1',
    length_max: '2',
    weight_min: '4',
    weight_max: '5',
    lifespan: '30',
    habitat: 'Rivers and streams',
    diet: 'Crayfish, small fish and aquatic insects',
    geo_range: 'Midwestern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/ff/Hellbender_Cryptobranchus_alleganiensis.jpg',
    id: 86,
  },
  {
    name: 'White Lion',
    latin_name: 'Panthera leo',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '5',
    length_max: '10',
    weight_min: '270',
    weight_max: '530',
    lifespan: '18',
    habitat: 'Savannah,  woodland and desert',
    diet: 'Hoofed mammals, hares, small birds and reptiles',
    geo_range: 'Timbavati, South Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/2f/White_Lion444.jpg',
    id: 186,
  },
  {
    name: 'Burmese Brown Mountain Tortoise',
    latin_name: 'Manouria emys emys',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '2',
    weight_min: '70',
    weight_max: '80',
    lifespan: '60',
    habitat: 'Forest',
    diet: 'Grass, leaves, fungi, and fruit',
    geo_range: 'Southeastern Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/6/69/Manouria-emys-asian-forest-tortoise.jpg',
    id: 48,
  },
  {
    name: 'Magellanic Penguin',
    latin_name: 'Spheniscus magellanicus',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2',
    length_max: '2.5',
    weight_min: '9',
    weight_max: '11',
    lifespan: '20',
    habitat: 'Ocean and coastal shores',
    diet: 'Small fish and squid',
    geo_range:
      'Pacific and Atlantic Oceans and coasts of southern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/cc/Magellanic_penguin%2C_Valdes_Peninsula%2C_e.jpg',
    id: 110,
  },
  {
    name: 'Indian Star Tortoise',
    latin_name: 'Geochelone elegans',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.85',
    length_max: '0.92',
    weight_min: '1.2',
    weight_max: '2.65',
    lifespan: '80',
    habitat: 'Forest, grassland and desert',
    diet: 'Grass, weeds, fruits and flowers',
    geo_range: 'Southern India and Sri Lanka',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/8/80/Davidraju_IMG_7365.jpg',
    id: 93,
  },
  {
    name: 'Madagascar Giant Day Gecko',
    latin_name: 'Phelsuma madagascariensis grandis',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.75',
    length_max: '1',
    weight_min: '0.13',
    weight_max: '0.15',
    lifespan: '15',
    habitat: 'Forest',
    diet: 'Insects and other small animals, fruit, and honey',
    geo_range: 'Northern Madagascar',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/8/8b/Madagascar_giant_day_gecko_%28Phelsuma_grandis%29_Nosy_Komba.jpg',
    id: 109,
  },
  {
    name: 'Magellanic Penguin',
    latin_name: 'Spheniscus magellanicus',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2',
    length_max: '2.5',
    weight_min: '9',
    weight_max: '11',
    lifespan: '20',
    habitat: 'Ocean and coastal shores',
    diet: 'Small fish and squid',
    geo_range:
      'Pacific and Atlantic Oceans and coasts of southern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/cc/Magellanic_penguin%2C_Valdes_Peninsula%2C_e.jpg',
    id: 110,
  },
  {
    name: 'Saddle-billed Stork',
    latin_name: 'Ephippiorhynchus senegalensis',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '4.75',
    length_max: '4.92',
    weight_min: '11',
    weight_max: '16',
    lifespan: '12',
    habitat: 'Freshwater marshes, rivers, floodplains and lake shores',
    diet: 'Mainly fish, some other small aquatic creatures, insects and carrion',
    geo_range: 'Central Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/e/e6/Saddle-billed_Stork_in_flight.jpg',
    id: 156,
  },
  {
    name: 'Impala',
    latin_name: 'Aepyceros melampus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '4.2',
    length_max: '4.7',
    weight_min: '99',
    weight_max: '132',
    lifespan: '15',
    habitat: 'Savannah and woodland',
    diet: 'Grasses and leaves',
    geo_range: 'Southern and East Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/e/e1/Trotting_impala_ram%2C_crop.jpg',
    id: 91,
  },
  {
    name: 'Fairy Bluebird',
    latin_name: 'Irena puella',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.75',
    length_max: '0.9',
    weight_min: '0.03',
    weight_max: '0.18',
    lifespan: '12',
    habitat: 'Forest',
    diet: 'Fruit, nectar, and insects',
    geo_range: 'South and Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3f/Fairy_bluebird_male_-_Irena_puella.jpg',
    id: 69,
  },
  {
    name: 'Hellbender',
    latin_name: 'Cryptobranchus alleganiensis',
    animal_type: 'Amphibian',
    active_time: 'Nocturnal',
    length_min: '1',
    length_max: '2',
    weight_min: '4',
    weight_max: '5',
    lifespan: '30',
    habitat: 'Rivers and streams',
    diet: 'Crayfish, small fish and aquatic insects',
    geo_range: 'Midwestern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/ff/Hellbender_Cryptobranchus_alleganiensis.jpg',
    id: 86,
  },
  {
    name: "Lady Ross' Turaco",
    latin_name: 'Musophaga rossae',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.25',
    length_max: '1.5',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '10',
    habitat: 'Forest',
    diet: 'Fruit and berries; some insects',
    geo_range: 'Central Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/fa/Musophaga_rossae_-Lady_Ross%27_Turaco_-Houston_Zoo.jpg',
    id: 101,
  },
  {
    name: 'Buff-crested bustard',
    latin_name: 'Eudpodotis ruficrista',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.4',
    length_max: '1.6',
    weight_min: '1.5',
    weight_max: '2',
    lifespan: '7',
    habitat: 'Semi-desert, bush, savanna and woodland',
    diet: 'Arthropods, seeds, fruit and grains',
    geo_range: 'Central southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/36/Crested_Bustard_-_Eupodotis_ruficrista_gindiana.jpg',
    id: 47,
  },
  {
    name: 'Eurasian Eagle Owl',
    latin_name: 'Bubo bubo',
    animal_type: 'Bird',
    active_time: 'Nocturnal',
    length_min: '2',
    length_max: '2.5',
    weight_min: '3.5',
    weight_max: '9',
    lifespan: '60',
    habitat: 'Rocky areas, woodland, and grassland',
    diet: 'Mammals, such as rabbits and rodents, and birds',
    geo_range: 'Europe and Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/14/Bubo_bubo_3_%28Martin_Mecnarowski%29.jpg',
    id: 68,
  },
  {
    name: 'Common Eider',
    latin_name: 'Somateria mollissima',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.7',
    length_max: '2',
    weight_min: '4',
    weight_max: '4.5',
    lifespan: '20',
    habitat: 'Marine waters near rocky seacoasts',
    diet: 'Fish, crustaceans, small animals',
    geo_range: 'Northern coasts of Europe, North America and eastern Siberia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/cd/Common_eider_male_at_Jones_Beach_%2804702%29.jpg',
    id: 56,
  },
  {
    name: 'Bearcat',
    latin_name: 'Arctitis binturong',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '2',
    length_max: '3.2',
    weight_min: '17',
    weight_max: '31',
    lifespan: '17',
    habitat: 'Tropical and subtropical forest',
    diet: 'Fruits, leaves, and small animals',
    geo_range: 'South and Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a7/Binturong_in_Overloon.jpg',
    id: 28,
  },
  {
    name: 'Nubian Goat',
    latin_name: 'Capra aegagrus hircus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '2.4',
    length_max: '2.5',
    weight_min: '150',
    weight_max: '175',
    lifespan: '20',
    habitat: 'Domestic habitat',
    diet: 'Hay and grain',
    geo_range: 'Raised domestically around the world',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/53/Anglo-Nubian_goat_%26_kid%2C_Bristol%2C_England_arp.jpg',
    id: 126,
  },
  {
    name: 'King Penguin',
    latin_name: 'Aptenodytes patagonius',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2.8',
    length_max: '3.1',
    weight_min: '20',
    weight_max: '45',
    lifespan: '25',
    habitat: 'Ocean and islands',
    diet: 'Squid, crustaceans, and fish',
    geo_range: 'Sub-Antarctic islands',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/be/SGI-2016-South_Georgia_%28Fortuna_Bay%29%E2%80%93King_penguin_%28Aptenodytes_patagonicus%29_04.jpg',
    id: 99,
  },
  {
    name: 'Asian Elephant',
    latin_name: 'Elephas maximus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '9',
    length_max: '10',
    weight_min: '10000',
    weight_max: '11000',
    lifespan: '47',
    habitat: 'Forest',
    diet: 'Grasses, leaves, barks, and fruits',
    geo_range: 'Southern and Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/98/Elephas_maximus_%28Bandipur%29.jpg',
    id: 19,
  },
  {
    name: "Lady Ross' Turaco",
    latin_name: 'Musophaga rossae',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.25',
    length_max: '1.5',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '10',
    habitat: 'Forest',
    diet: 'Fruit and berries; some insects',
    geo_range: 'Central Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/fa/Musophaga_rossae_-Lady_Ross%27_Turaco_-Houston_Zoo.jpg',
    id: 101,
  },
  {
    name: 'Red Panda',
    latin_name: 'Ailurus fulgens',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '1.5',
    length_max: '2',
    weight_min: '6.5',
    weight_max: '14',
    lifespan: '10',
    habitat: 'Mountain forest',
    diet: 'Primarily bamboo shoots and leaves; some roots, fruit, grasses, acorns, lichens, small animals',
    geo_range: 'South to Southeast Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/50/RedPandaFullBody.JPG',
    id: 145,
  },
  {
    name: 'Raggiana Bird-of-paradise',
    latin_name: 'Paradisaea raggiana',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.9',
    length_max: '1.1',
    weight_min: '0.44',
    weight_max: '0.75',
    lifespan: '8',
    habitat: 'Forest',
    diet: 'Fruit, berries, insects, frogs, and lizards',
    geo_range: 'New Guinea',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/c6/Raggiana_bird_of_paradise.jpg',
    id: 142,
  },
  {
    name: 'White Lion',
    latin_name: 'Panthera leo',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '5',
    length_max: '10',
    weight_min: '270',
    weight_max: '530',
    lifespan: '18',
    habitat: 'Savannah,  woodland and desert',
    diet: 'Hoofed mammals, hares, small birds and reptiles',
    geo_range: 'Timbavati, South Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/2f/White_Lion444.jpg',
    id: 186,
  },
  {
    name: 'Rhinoceros Hornbill',
    latin_name: 'Buceros rhinoceros',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '3.13',
    length_max: '3.46',
    weight_min: '4.5',
    weight_max: '6.5',
    lifespan: '35',
    habitat: 'Forest',
    diet: 'Fruit and small animals',
    geo_range: 'Malay peninsula and Borneo',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/6/6f/Buceros_rhinoceros_-Singapore_Zoo_-pair-8a.jpg',
    id: 150,
  },
  {
    name: 'Howler Monkey',
    latin_name: 'Alouatta caraya',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '2',
    weight_min: '9',
    weight_max: '22',
    lifespan: '18',
    habitat: 'Tropical forest',
    diet: 'Leaves, flowers and fruit',
    geo_range: 'South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/0d/Alouatta_guariba.jpg',
    id: 89,
  },
  {
    name: 'African Painted Dog',
    latin_name: 'Lycaon pictus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '2.5',
    length_max: '4',
    weight_min: '44',
    weight_max: '71',
    lifespan: '10',
    habitat: 'Savannah, woodland and semi-desert',
    diet: 'Primarily antelope; some warthogs, hares and small animals',
    geo_range: 'Central and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/ba/African_wild_dog_%28Lycaon_pictus_pictus%29.jpg',
    id: 4,
  },
  {
    name: 'African Pygmy Falcon',
    latin_name: 'Polihierax semitorquatus',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.6',
    length_max: '0.7',
    weight_min: '0.1',
    weight_max: '0.16',
    lifespan: '7',
    habitat: 'Savannah',
    diet: 'Insects, lizards, birds and rodents',
    geo_range: 'Eastern and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/7/74/African_Pygmy_Falcon_Female.jpg',
    id: 6,
  },
  {
    name: 'Trumpeter Swan',
    latin_name: 'Olor buccinator',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '5.8',
    length_max: '6',
    weight_min: '20',
    weight_max: '26',
    lifespan: '20',
    habitat: 'Freshwater rivers, lakes, ponds and marshes',
    diet: 'Aquatic vegetation',
    geo_range: 'Northwestern and central North America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/2d/Tumpeter1byWoodigo.JPG',
    id: 177,
  },
  {
    name: 'Pigeon Guillemot',
    latin_name: 'Cepphus columba',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.88',
    length_max: '1.2',
    weight_min: '1',
    weight_max: '1.1',
    lifespan: '15',
    habitat: 'Ocean and rocky coastal cliffs',
    diet: 'Fish and aquatic invertebrates',
    geo_range: 'Arctic and Pacific oceans and coasts of North America and Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/1b/Pigeon_guillemot.jpg',
    id: 135,
  },
  {
    name: 'Hamerkop',
    latin_name: 'Scopus umbretta',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.6',
    length_max: '1.8',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '20',
    habitat: 'Wetland, woodland, and savannah',
    diet: 'Frogs, fish, crustaceans, worms, and insects',
    geo_range: 'Sub-Saharan Africa, Madagascar, and southwestern Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/27/Hamerkop_%28Scopus_umbretta_umbretta%29.jpg',
    id: 85,
  },
  {
    name: 'Laughing Kookaburra',
    latin_name: 'Dacelo navaeguineae',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.4',
    length_max: '1.5',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '20',
    habitat: 'Forest',
    diet: 'Insects, snakes, lizards, rodents, and small birds',
    geo_range: 'Australia, Tasmania and New Zealand',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/9b/Laughing_kookaburra_dec08_02.jpg',
    id: 104,
  },
  {
    name: 'Cape Porcupine',
    latin_name: 'Hystrix africaeaustralis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '2.5',
    length_max: '3',
    weight_min: '40',
    weight_max: '65',
    lifespan: '15',
    habitat: 'Savannah, scrubland and forest',
    diet: 'Fruit, roots, tubers and bulbs',
    geo_range: 'Central and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/b4/Hystrix_africaeaustralis_Blijdorp_Rotterdam.JPG',
    id: 50,
  },
  {
    name: 'Southern Brazilian Ocelot',
    latin_name: 'Leopardus pardalis mitis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '2.4',
    length_max: '2.8',
    weight_min: '20',
    weight_max: '34',
    lifespan: '20',
    habitat: 'Tropical and subtropical forest',
    diet: 'Small mammals such as rodents, possums and armadillos, some reptiles and birds',
    geo_range: 'Central and eastern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/f8/Ocelot_%28Jaguatirica%29_Zoo_Itatiba.jpg',
    id: 165,
  },
  {
    name: 'Florida Manatee',
    latin_name: 'Trichechus manatus latirostris',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '8',
    length_max: '15',
    weight_min: '3000',
    weight_max: '2500',
    lifespan: '60',
    habitat: 'Costal wetlands',
    diet: 'Aquatic plants',
    geo_range: 'Southeastern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/1e/Manatee_at_Sea_World_Orlando_Mar_10.JPG',
    id: 72,
  },
  {
    name: 'African Penguin',
    latin_name: 'Spheniscus demersus',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2',
    length_max: '2.5',
    weight_min: '6',
    weight_max: '7',
    lifespan: '18',
    habitat: 'Ocean shoreline',
    diet: 'Fish and squid',
    geo_range: 'South Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/6/63/African_penguin_side_profile.jpg',
    id: 5,
  },
  {
    name: 'Komodo Dragon',
    latin_name: 'Varanus komodoensis',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '8',
    length_max: '10',
    weight_min: '150',
    weight_max: '175',
    lifespan: '50',
    habitat: 'Grasslands and rainforest',
    diet: 'Wild pigs, buffalo, deer, other animals, and carrion',
    geo_range: 'Indonesian islands',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/4/44/Komodo_dragon_%28Varanus_komodoensis%29_4.jpg',
    id: 100,
  },
  {
    name: 'African Pygmy Falcon',
    latin_name: 'Polihierax semitorquatus',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.6',
    length_max: '0.7',
    weight_min: '0.1',
    weight_max: '0.16',
    lifespan: '7',
    habitat: 'Savannah',
    diet: 'Insects, lizards, birds and rodents',
    geo_range: 'Eastern and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/7/74/African_Pygmy_Falcon_Female.jpg',
    id: 6,
  },
  {
    name: 'Trumpeter Swan',
    latin_name: 'Olor buccinator',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '5.8',
    length_max: '6',
    weight_min: '20',
    weight_max: '26',
    lifespan: '20',
    habitat: 'Freshwater rivers, lakes, ponds and marshes',
    diet: 'Aquatic vegetation',
    geo_range: 'Northwestern and central North America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/2d/Tumpeter1byWoodigo.JPG',
    id: 177,
  },
  {
    name: 'Pigeon Guillemot',
    latin_name: 'Cepphus columba',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.88',
    length_max: '1.2',
    weight_min: '1',
    weight_max: '1.1',
    lifespan: '15',
    habitat: 'Ocean and rocky coastal cliffs',
    diet: 'Fish and aquatic invertebrates',
    geo_range: 'Arctic and Pacific oceans and coasts of North America and Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/1b/Pigeon_guillemot.jpg',
    id: 135,
  },
  {
    name: 'Hamerkop',
    latin_name: 'Scopus umbretta',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.6',
    length_max: '1.8',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '20',
    habitat: 'Wetland, woodland, and savannah',
    diet: 'Frogs, fish, crustaceans, worms, and insects',
    geo_range: 'Sub-Saharan Africa, Madagascar, and southwestern Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/27/Hamerkop_%28Scopus_umbretta_umbretta%29.jpg',
    id: 85,
  },
  {
    name: 'Laughing Kookaburra',
    latin_name: 'Dacelo navaeguineae',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.4',
    length_max: '1.5',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '20',
    habitat: 'Forest',
    diet: 'Insects, snakes, lizards, rodents, and small birds',
    geo_range: 'Australia, Tasmania and New Zealand',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/9b/Laughing_kookaburra_dec08_02.jpg',
    id: 104,
  },
  {
    name: 'Cape Porcupine',
    latin_name: 'Hystrix africaeaustralis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '2.5',
    length_max: '3',
    weight_min: '40',
    weight_max: '65',
    lifespan: '15',
    habitat: 'Savannah, scrubland and forest',
    diet: 'Fruit, roots, tubers and bulbs',
    geo_range: 'Central and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/b4/Hystrix_africaeaustralis_Blijdorp_Rotterdam.JPG',
    id: 50,
  },
  {
    name: 'Southern Brazilian Ocelot',
    latin_name: 'Leopardus pardalis mitis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '2.4',
    length_max: '2.8',
    weight_min: '20',
    weight_max: '34',
    lifespan: '20',
    habitat: 'Tropical and subtropical forest',
    diet: 'Small mammals such as rodents, possums and armadillos, some reptiles and birds',
    geo_range: 'Central and eastern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/f8/Ocelot_%28Jaguatirica%29_Zoo_Itatiba.jpg',
    id: 165,
  },
  {
    name: 'Florida Manatee',
    latin_name: 'Trichechus manatus latirostris',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '8',
    length_max: '15',
    weight_min: '3000',
    weight_max: '2500',
    lifespan: '60',
    habitat: 'Costal wetlands',
    diet: 'Aquatic plants',
    geo_range: 'Southeastern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/1e/Manatee_at_Sea_World_Orlando_Mar_10.JPG',
    id: 72,
  },
  {
    name: 'African Penguin',
    latin_name: 'Spheniscus demersus',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2',
    length_max: '2.5',
    weight_min: '6',
    weight_max: '7',
    lifespan: '18',
    habitat: 'Ocean shoreline',
    diet: 'Fish and squid',
    geo_range: 'South Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/6/63/African_penguin_side_profile.jpg',
    id: 5,
  },
  {
    name: 'Komodo Dragon',
    latin_name: 'Varanus komodoensis',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '8',
    length_max: '10',
    weight_min: '150',
    weight_max: '175',
    lifespan: '50',
    habitat: 'Grasslands and rainforest',
    diet: 'Wild pigs, buffalo, deer, other animals, and carrion',
    geo_range: 'Indonesian islands',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/4/44/Komodo_dragon_%28Varanus_komodoensis%29_4.jpg',
    id: 100,
  },
  {
    name: 'African Lion',
    latin_name: 'Panthera leo',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '8.5',
    length_max: '10',
    weight_min: '330',
    weight_max: '530',
    lifespan: '16',
    habitat: 'Savannah, woodland, and desert',
    diet: 'Hoofed mammals, hares, small birds and reptiles',
    geo_range: 'Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/7/73/Lion_waiting_in_Namibia.jpg',
    id: 3,
  },
  {
    name: 'Komodo Dragon',
    latin_name: 'Varanus komodoensis',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '8',
    length_max: '10',
    weight_min: '150',
    weight_max: '175',
    lifespan: '50',
    habitat: 'Grasslands and rainforest',
    diet: 'Wild pigs, buffalo, deer, other animals, and carrion',
    geo_range: 'Indonesian islands',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/4/44/Komodo_dragon_%28Varanus_komodoensis%29_4.jpg',
    id: 100,
  },
  {
    name: 'Red-crowned crane',
    latin_name: 'Grus japonensis',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '5',
    length_max: '5.2',
    weight_min: '15',
    weight_max: '22',
    lifespan: '25',
    habitat: 'Wetlands',
    diet: 'Aquatic animals and plants',
    geo_range: 'East Asia ',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/5a/Grus_japonensis_-Hokkaido%2C_Japan_-several-8_%281%29.jpg',
    id: 148,
  },
  {
    name: 'Blue and Gold Macaw',
    latin_name: 'Ara ararauna',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2.8',
    length_max: '3.2',
    weight_min: '1.3',
    weight_max: '2',
    lifespan: '50',
    habitat: 'Wetlands and forest',
    diet: 'Seeds, fruits, and nuts',
    geo_range: 'Central and South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/6/6d/Blue-and-Yellow-Macaw.jpg',
    id: 37,
  },
  {
    name: 'Aruba Island Rattlesnake',
    latin_name: 'Crotalus unicolor',
    animal_type: 'Reptile',
    active_time: 'Nocturnal',
    length_min: '3',
    length_max: '3.3',
    weight_min: '2',
    weight_max: '2.2',
    lifespan: '20',
    habitat: 'Dry regions, rocky hillsides and desert',
    diet: 'Small mammals, birds and lizards',
    geo_range: 'Aruba Island',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/0f/Aruba_Island_Rattle_Snake.jpg',
    id: 18,
  },
  {
    name: 'Nubian Goat',
    latin_name: 'Capra aegagrus hircus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '2.4',
    length_max: '2.5',
    weight_min: '150',
    weight_max: '175',
    lifespan: '20',
    habitat: 'Domestic habitat',
    diet: 'Hay and grain',
    geo_range: 'Raised domestically around the world',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/53/Anglo-Nubian_goat_%26_kid%2C_Bristol%2C_England_arp.jpg',
    id: 126,
  },
  {
    name: 'Amazon Milk Frog',
    latin_name: 'Trachycephalus resinifictrix',
    animal_type: 'Amphibian',
    active_time: 'Nocturnal',
    length_min: '0.21',
    length_max: '0.33',
    weight_min: '0.05',
    weight_max: '0.05',
    lifespan: '25',
    habitat: 'Tropical rainforest',
    diet: 'Insects, spiders, and other small animals',
    geo_range: 'Northern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/12/Amazon_Milk_Frog_%28Trachycephalus_resinifictrix%29%2C_CMN.jpg',
    id: 10,
  },
  {
    name: 'Lesser Kudu',
    latin_name: 'Tragelaphus imberbis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '5.2',
    length_max: '5.7',
    weight_min: '121',
    weight_max: '243',
    lifespan: '15',
    habitat: 'Shrubland, woodland and savannah',
    diet: 'Leaves, twigs, fruit and seed pods',
    geo_range: 'East Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/b8/Lesser_Kudu_Male_%28Tragelaphus_imberbis%29.jpg',
    id: 105,
  },
  {
    name: 'Laughing Kookaburra',
    latin_name: 'Dacelo navaeguineae',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.4',
    length_max: '1.5',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '20',
    habitat: 'Forest',
    diet: 'Insects, snakes, lizards, rodents, and small birds',
    geo_range: 'Australia, Tasmania and New Zealand',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/9b/Laughing_kookaburra_dec08_02.jpg',
    id: 104,
  },
  {
    name: 'Rhinoceros Hornbill',
    latin_name: 'Buceros rhinoceros',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '3.13',
    length_max: '3.46',
    weight_min: '4.5',
    weight_max: '6.5',
    lifespan: '35',
    habitat: 'Forest',
    diet: 'Fruit and small animals',
    geo_range: 'Malay peninsula and Borneo',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/6/6f/Buceros_rhinoceros_-Singapore_Zoo_-pair-8a.jpg',
    id: 150,
  },
  {
    name: 'Red-crowned crane',
    latin_name: 'Grus japonensis',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '5',
    length_max: '5.2',
    weight_min: '15',
    weight_max: '22',
    lifespan: '25',
    habitat: 'Wetlands',
    diet: 'Aquatic animals and plants',
    geo_range: 'East Asia ',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/5a/Grus_japonensis_-Hokkaido%2C_Japan_-several-8_%281%29.jpg',
    id: 148,
  },
  {
    name: 'Longnose Gar',
    latin_name: 'Lepisosteus osseus',
    animal_type: 'Fish',
    active_time: 'Nocturnal',
    length_min: '2',
    length_max: '6',
    weight_min: '1.1',
    weight_max: '7.7',
    lifespan: '20',
    habitat: 'Rivers, lakes, reserviors and estuaries',
    diet: 'Small fish',
    geo_range: 'North America east of the Mississippi River',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a6/Longnose_gar%2C_Boston_Aquarium.JPG',
    id: 108,
  },
  {
    name: 'Pancake Tortoise',
    latin_name: 'Malacochersus tornieri',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.46',
    length_max: '0.54',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '30',
    habitat: 'Rocky Outcrops',
    diet: 'Grasses, leaves, and fruit',
    geo_range: 'Eastern central Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/93/Malacochersus_tornieri.jpg',
    id: 132,
  },
  {
    name: 'Salmon-Crested Cockatoo',
    latin_name: 'Cacatua moluccensis',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.51',
    length_max: '1.71',
    weight_min: '1.5',
    weight_max: '2.2',
    lifespan: '80',
    habitat: 'Forest and mountains',
    diet: 'Seeds and fruit',
    geo_range: 'Southern Moluccas, Indonesia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/b8/Cacatua_moluccensis_-Cincinnati_Zoo-8a.jpg',
    id: 157,
  },
  {
    name: 'Southern Rockhopper Penguin',
    latin_name: 'Eudyptes chrysocome',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.75',
    length_max: '1.8',
    weight_min: '4.5',
    weight_max: '9.5',
    lifespan: '23',
    habitat: 'Ocean, rocky cliffs, grassland and coastal shores',
    diet: 'Krill, crustaceans, fish, and squid',
    geo_range: 'Sub-Antarctic islands and southern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/e/ee/Gorfou_sauteur_-_Rockhopper_Penguin.jpg',
    id: 167,
  },
  {
    name: 'Rough Green Snake',
    latin_name: 'Opheodrys aestivus',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '1.83',
    length_max: '2.67',
    weight_min: '0.02',
    weight_max: '0.12',
    lifespan: '10',
    habitat: 'Moist woodland',
    diet: 'Insects and spiders',
    geo_range: 'Southeastern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/bd/Rough_Green_Snake.jpg',
    id: 153,
  },
  {
    name: 'Fennec Fox',
    latin_name: 'Vulpes zerda',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '9.5',
    length_max: '16',
    weight_min: '2.3',
    weight_max: '3.3',
    lifespan: '11',
    habitat: 'Desert',
    diet: 'Fruit, seeds, eggs, termites, and lizards',
    geo_range: 'Northern Africa and western Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/9c/Fennec_Fox.jpg',
    id: 70,
  },
  {
    name: 'Parma Wallaby',
    latin_name: 'Macropus parma',
    animal_type: 'Marsupial',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '2',
    weight_min: '10',
    weight_max: '11',
    lifespan: '7',
    habitat: 'Forest and grassland',
    diet: 'Grass',
    geo_range: 'Australia and New Zealand',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a2/Parma_wallaby_crop2.jpg',
    id: 133,
  },
  {
    name: 'Titicaca Water Frog',
    latin_name: 'Telmatobius culeus',
    animal_type: 'Amphibian',
    active_time: 'Nocturnal',
    length_min: '0.42',
    length_max: '0.46',
    weight_min: '0.6',
    weight_max: '0.9',
    lifespan: '20',
    habitat: 'Freshwater lakes and welands',
    diet: 'Crustaceans, snails, and other small animals',
    geo_range: 'Lake Titicaca Bolivia and Peru',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3a/Vodnice_posv%C3%A1tn%C3%A1_zoo_praha_1.jpg',
    id: 176,
  },
  {
    name: 'Southern Copperhead',
    latin_name: 'Agkistrodon contortrix contortix',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '4',
    length_max: '4.5',
    weight_min: '0.5',
    weight_max: '0.75',
    lifespan: '18',
    habitat: 'Woodlands and rocky hillsides',
    diet: 'Small mammals, birds, frogs, and insects',
    geo_range: 'Central and Eastern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/ce/Copperhead_%28Agkistrodon_contortrix%29_photographed_in_Liberty_Co.%2C_Texas._W._L._Farr.jpg',
    id: 166,
  },
  {
    name: 'Black Rhinoceros',
    latin_name: 'Diceros bicornis',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '4.7',
    length_max: '5.2',
    weight_min: '2000',
    weight_max: '2900',
    lifespan: '40',
    habitat: 'Woodland and scrubland',
    diet: 'Woody plants, herbs, and fruits',
    geo_range: 'Central and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/22/2012_Black_Rhinoceros_Gemsbokvlakte.jpg',
    id: 33,
  },
  {
    name: 'Potto',
    latin_name: 'Perodictus potto',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '1',
    length_max: '1.3',
    weight_min: '1.7',
    weight_max: '3.7',
    lifespan: '25',
    habitat: 'Tropical forest',
    diet: 'Fruit, insects and other small animals',
    geo_range: 'Western and Central Africa',
    image_link:
      'https://static.wikia.nocookie.net/animals/images/6/67/Potto.jpg',
    id: 139,
  },
  {
    name: 'Rough Green Snake',
    latin_name: 'Opheodrys aestivus',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '1.83',
    length_max: '2.67',
    weight_min: '0.02',
    weight_max: '0.12',
    lifespan: '10',
    habitat: 'Moist woodland',
    diet: 'Insects and spiders',
    geo_range: 'Southeastern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/bd/Rough_Green_Snake.jpg',
    id: 153,
  },
  {
    name: 'Alligator Gar',
    latin_name: 'Lepisosteus spatula',
    animal_type: 'Fish',
    active_time: 'Nocturnal',
    length_min: '8',
    length_max: '10',
    weight_min: '250',
    weight_max: '300',
    lifespan: '50',
    habitat: 'Rivers, lakes and other bodies of fresh and brackish water',
    diet: 'Fish and other small animals',
    geo_range: 'North America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/16/Alligator_Gar_10.JPG',
    id: 7,
  },
  {
    name: 'Black-footed Cat',
    latin_name: 'Felis nigripes',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '1.1',
    length_max: '1.7',
    weight_min: '3.3',
    weight_max: '6.5',
    lifespan: '5',
    habitat: 'Desert, savannah, and scrubland',
    diet: 'Mice, insects, spiders, lizards, and birds',
    geo_range: 'Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/da/Zoo_Wuppertal_Schwarzfusskatze.jpg',
    id: 36,
  },
  {
    name: 'Laughing Kookaburra',
    latin_name: 'Dacelo navaeguineae',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.4',
    length_max: '1.5',
    weight_min: '0.8',
    weight_max: '1',
    lifespan: '20',
    habitat: 'Forest',
    diet: 'Insects, snakes, lizards, rodents, and small birds',
    geo_range: 'Australia, Tasmania and New Zealand',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/9b/Laughing_kookaburra_dec08_02.jpg',
    id: 104,
  },
  {
    name: 'Poison Dart Frog',
    latin_name: 'Dendrobates tinctorius',
    animal_type: 'Amphibian',
    active_time: 'Diurnal',
    length_min: '0.1',
    length_max: '0.2',
    weight_min: '0.06',
    weight_max: '0.07',
    lifespan: '10',
    habitat: 'Tropical rainforest',
    diet: 'Ants, termites, and small flies',
    geo_range: 'Northern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/04/F%C3%A4rberfrosch_Dendrobates_tinctorius.jpg',
    id: 138,
  },
  {
    name: 'Ring-tailed Lemur',
    latin_name: 'Lemur catta',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.3',
    length_max: '1.5',
    weight_min: '5',
    weight_max: '8',
    lifespan: '16',
    habitat: 'Forest',
    diet: 'Fruit, leaves, flowers and insects',
    geo_range: 'Southern and Southwestern Madagascar',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/0b/Ring-tailed_lemur_%28Lemur_catta%29.jpg',
    id: 151,
  },
  {
    name: 'Screaming Hairy Armadillo',
    latin_name: 'Chaetophractus vellerosus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1',
    length_max: '1.3',
    weight_min: '1.75',
    weight_max: '2',
    lifespan: '16',
    habitat: 'Desert, grassland, scrubland, and forest',
    diet: 'Plants, insects, and other small animals',
    geo_range: 'Central South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/5d/Chaetophractus_vellerosus3.jpg',
    id: 160,
  },
  {
    name: 'Vampire Bat',
    latin_name: 'Desmodus rotundus',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '0.23',
    length_max: '0.32',
    weight_min: '0.08',
    weight_max: '0.1',
    lifespan: '9',
    habitat: 'Rainforest, scrub, and desert',
    diet: 'Mammal blood',
    geo_range: 'Mexico, Central and South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/32/Desmodus_rotundus_A_Catenazzi.jpg',
    id: 180,
  },
  {
    name: 'Black-footed Cat',
    latin_name: 'Felis nigripes',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '1.1',
    length_max: '1.7',
    weight_min: '3.3',
    weight_max: '6.5',
    lifespan: '5',
    habitat: 'Desert, savannah, and scrubland',
    diet: 'Mice, insects, spiders, lizards, and birds',
    geo_range: 'Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/da/Zoo_Wuppertal_Schwarzfusskatze.jpg',
    id: 36,
  },
  {
    name: 'Red-eared Slider',
    latin_name: 'Trachemys scripta elegans',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.42',
    length_max: '0.92',
    weight_min: '1.5',
    weight_max: '2',
    lifespan: '20',
    habitat: 'Freshwater ponds and streams',
    diet: 'Fish, mollusks, and insects',
    geo_range: 'Southern and Midwestern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/96/RedEaredSlider05.jpg',
    id: 149,
  },
  {
    name: 'Howler Monkey',
    latin_name: 'Alouatta caraya',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '2',
    weight_min: '9',
    weight_max: '22',
    lifespan: '18',
    habitat: 'Tropical forest',
    diet: 'Leaves, flowers and fruit',
    geo_range: 'South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/0d/Alouatta_guariba.jpg',
    id: 89,
  },
  {
    name: 'Azureus Cichlid',
    latin_name: 'Copadichromis azureus',
    animal_type: 'Fish',
    active_time: 'Diurnal',
    length_min: '0.42',
    length_max: '0.55',
    weight_min: '0.5',
    weight_max: '0.75',
    lifespan: '8',
    habitat: 'Lakes',
    diet: 'Plankton',
    geo_range: 'Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/0/04/Copadichromis_azureus.jpg',
    id: 22,
  },
  {
    name: 'Masai Giraffe',
    latin_name: 'Giraffa camelopardalis tippelskirchi',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '15',
    length_max: '17',
    weight_min: '1200',
    weight_max: '4250',
    lifespan: '13',
    habitat: 'Savanna and woodland',
    diet: 'Leaves, shoots, and fruits',
    geo_range: 'Southern Kenya and Tanzania',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3b/Mannetjes_masaigiraffe_in_de_Serengeti%2C_Tanzania%2C_-12_januari_2013_a.jpg',
    id: 114,
  },
  {
    name: 'Black-breasted Leaf Turtle',
    latin_name: 'Geoemyda spengleri',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '0.2',
    length_max: '0.35',
    weight_min: '0.2',
    weight_max: '0.4',
    lifespan: '20',
    habitat: 'Mountain forest',
    diet: 'Invertebrates and fruit',
    geo_range: 'China and Vietnam',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/d6/Stavenn_Geoemyda_spengleri.jpg',
    id: 35,
  },
  {
    name: 'Visayan Warty Pig',
    latin_name: 'Sus cebifrons',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '3',
    length_max: '4',
    weight_min: '55',
    weight_max: '90',
    lifespan: '15',
    habitat: 'Rainforest',
    diet: 'Fruits, roots and crops',
    geo_range: 'Philippines',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/8/89/VisayanWartyPig01.jpg',
    id: 183,
  },
  {
    name: 'Greater Bushbaby',
    latin_name: 'Otolemur garnetti',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '0.75',
    length_max: '0.83',
    weight_min: '1.5',
    weight_max: '1.8',
    lifespan: '14',
    habitat: 'Forest',
    diet: 'Fruit and insects',
    geo_range: 'Eastern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/de/Garnett%27s_Galago_%28Greater_Bushbaby%29.jpg',
    id: 77,
  },
  {
    name: 'Aye-aye',
    latin_name: 'Daubentonia madagascariensis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '1',
    length_max: '1.3',
    weight_min: '5',
    weight_max: '6',
    lifespan: '23',
    habitat: 'Forest and swamp',
    diet: 'Insect larva, nuts, and fruits',
    geo_range: 'Madagascar',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a2/Wild_aye_aye.jpg',
    id: 21,
  },
  {
    name: 'Burmese Python',
    latin_name: 'Python molurus',
    animal_type: 'Reptile',
    active_time: 'Nocturnal',
    length_min: '16',
    length_max: '25',
    weight_min: '140',
    weight_max: '200',
    lifespan: '20',
    habitat: 'Tropical forest',
    diet: 'Birds, mammals, and reptiles',
    geo_range: 'Southern and Southeastern Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/8/85/Burmese_python_%286887388927%29.jpg',
    id: 49,
  },
  {
    name: 'Cape Porcupine',
    latin_name: 'Hystrix africaeaustralis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '2.5',
    length_max: '3',
    weight_min: '40',
    weight_max: '65',
    lifespan: '15',
    habitat: 'Savannah, scrubland and forest',
    diet: 'Fruit, roots, tubers and bulbs',
    geo_range: 'Central and Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/b4/Hystrix_africaeaustralis_Blijdorp_Rotterdam.JPG',
    id: 50,
  },
  {
    name: 'Tawny Frogmouth',
    latin_name: 'Podargus strigoides',
    animal_type: 'Bird',
    active_time: 'Nocturnal',
    length_min: '1.4',
    length_max: '1.7',
    weight_min: '1',
    weight_max: '1.3',
    lifespan: '20',
    habitat: 'Forest',
    diet: 'Insects, spiders, worms and other small animals',
    geo_range: 'Australia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/9/90/Tawny_Frogmouth_%28Coverdale%29.jpg',
    id: 172,
  },
  {
    name: 'Alpaca',
    latin_name: 'Vicugna pacos',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '3',
    length_max: '3.5',
    weight_min: '120',
    weight_max: '145',
    lifespan: '25',
    habitat: 'Grasslands',
    diet: 'Grass',
    geo_range: 'South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/d/db/Alpaca_%2831562329701%29.jpg',
    id: 9,
  },
  {
    name: 'Galapagos Tortoise',
    latin_name: 'Geochelone nigra microphyes',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '5',
    length_max: '6',
    weight_min: '300',
    weight_max: '550',
    lifespan: '100',
    habitat: 'Dry grasslands',
    diet: 'Cactus, fruit, flowers, leaves, and grasses',
    geo_range: 'Galapagos Islands',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/4/42/Galapagos_giant_tortoise_Geochelone_elephantopus.jpg',
    id: 74,
  },
  {
    name: 'Impala',
    latin_name: 'Aepyceros melampus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '4.2',
    length_max: '4.7',
    weight_min: '99',
    weight_max: '132',
    lifespan: '15',
    habitat: 'Savannah and woodland',
    diet: 'Grasses and leaves',
    geo_range: 'Southern and East Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/e/e1/Trotting_impala_ram%2C_crop.jpg',
    id: 91,
  },
  {
    name: 'Eastern Bongo',
    latin_name: 'Tragelaphus eurycerus',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '3.5',
    length_max: '4.5',
    weight_min: '460',
    weight_max: '890',
    lifespan: '9',
    habitat: 'Lowland and montane forest',
    diet: 'Bushes, leaves, grasses, flowers, bark, and roots',
    geo_range: 'Central Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/5/59/Eastern_Bongo_at_Jacksonville_Zoo.jpg',
    id: 64,
  },
  {
    name: 'Florida Manatee',
    latin_name: 'Trichechus manatus latirostris',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '8',
    length_max: '15',
    weight_min: '3000',
    weight_max: '2500',
    lifespan: '60',
    habitat: 'Costal wetlands',
    diet: 'Aquatic plants',
    geo_range: 'Southeastern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/1/1e/Manatee_at_Sea_World_Orlando_Mar_10.JPG',
    id: 72,
  },
  {
    name: 'Crested Coua',
    latin_name: 'Coua cristata',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.3',
    length_max: '1.5',
    weight_min: '0.2',
    weight_max: '0.23',
    lifespan: '15',
    habitat: 'Forest, savanna, and shrubland habitats',
    diet: 'Insects, fruits, berries, seeds, snails and chameleons',
    geo_range: 'Madagascar',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/3/3d/Crested_Coua_RWD3.jpg',
    id: 60,
  },
  {
    name: 'Trumpeter Swan',
    latin_name: 'Olor buccinator',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '5.8',
    length_max: '6',
    weight_min: '20',
    weight_max: '26',
    lifespan: '20',
    habitat: 'Freshwater rivers, lakes, ponds and marshes',
    diet: 'Aquatic vegetation',
    geo_range: 'Northwestern and central North America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/2/2d/Tumpeter1byWoodigo.JPG',
    id: 177,
  },
  {
    name: 'White-naped Pheasant Pigeon',
    latin_name: 'Otidiphaps nobilis aruensis',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '1.2',
    length_max: '1.5',
    weight_min: '1',
    weight_max: '1.1',
    lifespan: '5',
    habitat: 'Rainforest',
    diet: 'Seeds and fruits',
    geo_range: 'New Guinea and surrounding islands',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/e/ee/Otidiphaps_nobilis_-Cincinnati_Zoo%2C_Ohio%2C_USA-8a.jpg',
    id: 191,
  },
  {
    name: 'Matamata',
    latin_name: 'Chelus fimbriatus',
    animal_type: 'Reptile',
    active_time: 'Nocturnal',
    length_min: '1.1',
    length_max: '1.3',
    weight_min: '35',
    weight_max: '38',
    lifespan: '30',
    habitat: 'Shallow pools and streams',
    diet: 'Fish',
    geo_range: 'Northern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/7/7f/2009_Chelus_fimbriatus.JPG',
    id: 116,
  },
  {
    name: 'Angolan Python',
    latin_name: 'Python anchietae',
    animal_type: 'Reptile',
    active_time: 'Nocturnal',
    length_min: '3.3',
    length_max: '5.9',
    weight_min: '2.5',
    weight_max: '3.3',
    lifespan: '30',
    habitat: 'Arid rocky areas and bushland',
    diet: 'Rodents and birds',
    geo_range: 'Southern Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/4/4a/Angolan_Dwarf_Python_%28Python_anchietae%29.jpg',
    id: 16,
  },
  {
    name: 'Lesser Kudu',
    latin_name: 'Tragelaphus imberbis',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '5.2',
    length_max: '5.7',
    weight_min: '121',
    weight_max: '243',
    lifespan: '15',
    habitat: 'Shrubland, woodland and savannah',
    diet: 'Leaves, twigs, fruit and seed pods',
    geo_range: 'East Africa',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/b/b8/Lesser_Kudu_Male_%28Tragelaphus_imberbis%29.jpg',
    id: 105,
  },
  {
    name: 'Scarlet Ibis',
    latin_name: 'Eudocimus ruber',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '2.1',
    length_max: '2.2',
    weight_min: '1.3',
    weight_max: '1.4',
    lifespan: '12',
    habitat: 'Coastal wetlands',
    diet: 'Small crayfish, snails and amphibians',
    geo_range: 'Northern South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/f7/Scarlet_Ibis_SMTC.jpg',
    id: 159,
  },
  {
    name: 'Raggiana Bird-of-paradise',
    latin_name: 'Paradisaea raggiana',
    animal_type: 'Bird',
    active_time: 'Diurnal',
    length_min: '0.9',
    length_max: '1.1',
    weight_min: '0.44',
    weight_max: '0.75',
    lifespan: '8',
    habitat: 'Forest',
    diet: 'Fruit, berries, insects, frogs, and lizards',
    geo_range: 'New Guinea',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/c/c6/Raggiana_bird_of_paradise.jpg',
    id: 142,
  },
  {
    name: 'Green Basilisk',
    latin_name: 'Basiliscus plumifrons',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '2',
    length_max: '3',
    weight_min: '0.5',
    weight_max: '0.6',
    lifespan: '10',
    habitat: 'Tropical rainforest',
    diet: 'Seeds, fruit, leaves, insects and other small animals',
    geo_range: 'Central America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/f/f3/Green_Basilisk%2C_Alajuela%2C_Costa_Rica.jpg',
    id: 80,
  },
  {
    name: 'Clouded Leopard',
    latin_name: 'Neofelis nebulosa',
    animal_type: 'Mammal',
    active_time: 'Nocturnal',
    length_min: '2',
    length_max: '3.5',
    weight_min: '24',
    weight_max: '44',
    lifespan: '13',
    habitat: 'Forest, grassland, and wetland',
    diet: 'Primates, deer, wild boar, porcupines, small mammals, and birds',
    geo_range: 'Southeastern Asia',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/ab/Clouded_Leopard_Neofelis_nebulosa_by_Dr_Raju_Kasambe_DSC_7497_%2828%29.JPG',
    id: 55,
  },
  {
    name: 'Black Howler Monkey',
    latin_name: 'Alouatta caraya',
    animal_type: 'Mammal',
    active_time: 'Diurnal',
    length_min: '1.5',
    length_max: '2',
    weight_min: '9',
    weight_max: '22',
    lifespan: '18',
    habitat: 'Tropical forest',
    diet: 'Leaves, flowers and fruit',
    geo_range: 'South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/ae/Black_Howler_Monkey_Portrait_1.jpg',
    id: 31,
  },
  {
    name: 'Rainbow Boa',
    latin_name: 'Epicrates cenchria',
    animal_type: 'Reptile',
    active_time: 'Nocturnal',
    length_min: '5',
    length_max: '7',
    weight_min: '2',
    weight_max: '5',
    lifespan: '20',
    habitat: 'Woodland and savanna',
    diet: 'Small mammals and birds',
    geo_range: 'South America',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/a/a4/EpicratesCenchriaCenchria1.jpg',
    id: 143,
  },
  {
    name: 'Alligator Snapping Turtle',
    latin_name: 'Macroclemys temmnicki',
    animal_type: 'Reptile',
    active_time: 'Diurnal',
    length_min: '1.3',
    length_max: '2.7',
    weight_min: '200',
    weight_max: '225',
    lifespan: '70',
    habitat: 'Fresh water lakes and rivers',
    diet: 'Fish',
    geo_range: 'Freshwaters of the Southeastern United States',
    image_link:
      'https://upload.wikimedia.org/wikipedia/commons/8/88/Alligator_snapping_turtle.jpg',
    id: 8,
  },
];

let dataObj = {};

data = data.map((animal) => {
  animal.price = Math.floor(Math.random() * 10000 + 100);
  dataObj[animal.id] = animal;
  return animal;
});

const fs = require('fs');

fs.writeFile(
  '/script/seedoutput.js',
  JSON.stringify(Object.values(dataObj)),
  function (err) {
    if (err) return console.log(err);
    console.log('Hello World > helloworld.txt');
  }
);

console.log('outputed');
